#!/usr/bin/env python3
"""Generate a new portfolio site design using PydanticAI and Gemini."""

import os
import sys
import re
from datetime import datetime
from pydantic_ai import Agent


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)
    prompt_path = os.path.join(repo_root, "prompt.txt")

    with open(prompt_path, "r") as f:
        base_instructions = f.read()

    index_path = os.path.join(repo_root, "index.html")
    current_html = ""
    if os.path.exists(index_path):
        with open(index_path, "r") as f:
            current_html = f.read()

    agent = Agent(
        'openrouter:google/gemini-3-flash-preview',
        system_prompt=base_instructions
    )

    today = datetime.now().strftime("%Y-%m-%d")
    
    # Check for manual style hint
    style_hint = os.environ.get("STYLE_HINT", "")
    
    extra_instruction = "Surprise me."
    if style_hint:
        extra_instruction = f"IMPORTANT: Follow this specific style focus: {style_hint}"

    # Run the agent
    # We provide the current design and ask for something different.
    user_prompt = f"""Generate the weekly redesign for {today}.
    
    Here is the CURRENT design (index.html) for reference:
    ```html
    {current_html}
    ```
    
    INSTRUCTION: Create a completely NEW and UNIQUE design. Do not just tweak the current one.
    The new design should be visually distinct from the code above in terms of layout, typography, and theme.
    {extra_instruction}"""
        
    result = agent.run_sync(user_prompt)
    html = result.output.strip()

    html = re.sub(r"^```html?\s*\n?", "", html)
    html = re.sub(r"\n?```\s*$", "", html)
    html = html.strip()

    # Inject mandatory top banner
    banner_html = """
<div id="mandatory-bot-banner" style="background-color: #000; color: #fff; text-align: center; padding: 10px; font-weight: bold; font-family: sans-serif; position: relative; width: 100%; z-index: 10000; border-bottom: 1px solid #333;">
    This website design and code are automatically generated and updated weekly by an LLM. <a href="/prompt.txt" style="color: #fff; text-decoration: underline;">Read the prompt here</a>.
    <button onclick="document.getElementById('mandatory-bot-banner').remove()" style="position: absolute; right: 10px; top: 50%; transform: translateY(-50%); background: none; border: none; color: #fff; font-size: 20px; cursor: pointer;">&times;</button>
</div>
"""
    
    if re.search(r"<body[^>]*>", html, re.IGNORECASE):
        html = re.sub(r"(<body[^>]*>)", r"\1\n" + banner_html, html, count=1, flags=re.IGNORECASE)
    else:
        html = banner_html + html

    checks = [
        ("<!DOCTYPE html>", "Missing DOCTYPE"),
        ("bg.webm", "Missing bg.webm reference"),
        ("rss2json", "Missing blog RSS fetch"),
        ("Akshay", "Missing name"),
        ("generated by a bot", "Missing bot attribution"),
    ]

    for check, msg in checks:
        if check.lower() not in html.lower():
            print(f"WARNING: {msg}")

    if not html.startswith("<!DOCTYPE") and not html.startswith("<!doctype"):
        print("ERROR: Output doesn't look like valid HTML")
        print(f"First 200 chars: {html[:200]}")
        sys.exit(1)

    output_path = os.path.join(repo_root, "index.html")
    with open(output_path, "w") as f:
        f.write(html)

    print(f"Successfully generated new design ({len(html)} bytes)")
    print(f"Written to: {output_path}")

if __name__ == "__main__":
    main()
